### ISSUE TITLE
Non-Protocol Intersection

### ISSUE THREAD

**Issue by gentlegiantJGC** [klausweiss/typing-protocol-intersection#12]
Is there a reason why this can't be used with non-protocol classes?
This seems like the solution I have been looking for but I need it to work with non-protocol classes.

I hope that one day Python will have a native intersection type but until then this could be a useful stopgap.

**Comment by klausweiss** [comment]
> Is there a reason why this can't be used with non-protocol classes?

The implementation is explicitly only targeting protocols, as it's a relatively simple problem to solve. This plugin will only ever support intersection of protocols (hence the name ;)).

General type intersection is a much more involving problem. There's a discussion on the topic in the python/typing repository https://github.com/python/typing/issues/213 and there's actually a PEP in the works to make this happen https://github.com/CarliJoy/intersection_examples I remember reading excellent examples as to why it's not so simple somewhere in that thread, but I don't have them at hand anymore unfortunately, you'll have to dig if you're interested.

**Comment by gentlegiantJGC** [comment]
Do you know if a MyPy plugin exists/could be written to allow a normal class to be promoted to a protocol so that it could be used with your intersection?

I have been experimenting with your code and setting is_protocol=True on all the classes passed to the intersection allows your plugin to work with non-protocol classes however this effects the class outside of the intersection.

**Comment by klausweiss** [comment]
>Do you know if a MyPy plugin exists/could be written to allow a normal class to be promoted to a protocol so that it could be used with your intersection?

Sorry, I don't know. 

>I have been experimenting with your code and setting is_protocol=True on all the classes passed to the intersection allows your plugin to work with non-protocol classes however this effects the class outside of the intersection.

I would advise against modifying this plugin in such way (making it do things it's not supposed to do), unless you're familiar with internals of mypy itself. The goal of a type checker ultimately is to make you trust the code more. If you can't trust the type-checker, it misses the point.
